### ISSUE TITLE
Getting flooded with incorrect results

### ISSUE THREAD

**Issue by JoakimSoderberg** [tsileo/cube-client#6]
- When doing `c.metric("sum(a)")` I get an exception because "a" doesn't exist. This is correct.
- When doing `c.metric("sum(aa)")` I get a list with 10001 results of incorrect values, "aa" doesn't exist either. But shouldn't I get the same result as for "a"

See example:

```
>>> from cube import Cube
>>> c = Cube()
>>> c.metric("sum(a)") # Try getting an non-existing key. Result in an exception
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/cube_client-0.1-py2.7.egg/cube.py", line 61, in metric
    return self.make_query("metric", expression, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cube_client-0.1-py2.7.egg/cube.py", line 47, in make_query
    r.raise_for_status()
  File "/usr/local/lib/python2.7/dist-packages/requests-1.2.0-py2.7.egg/requests/models.py", line 670, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request

>>> c.metric("sum(aa)")  # Try the same thing, but now a two letter name... Error!
[{u'value': 0, u'time': u'2013-05-19T18:08:50.000Z'}, {u'value': 0, u'time': u'2013-05-19T18:09:00.000Z'}, {u'value': 0, u'time': u'2013-05-19T18:09:10.000Z'}, {u'value': 0, u'time': u'2013-05-19T18:09:20.000Z'}, {u'value': 0, u'time': u'2013-05-19T18:09:30.000Z'}, {u'value': 0, u'time': u'2013-05-19T18:09:40.000Z'}, {u'value': 0, u'time': u'2013-05-19T18:09:50.000Z'}, {u'value': 0, u'time': u'2013-05-19T18:10:00.000Z'}, {u'value': 0, u'time': u'2013-05-19T18:10:10.000Z'}, {u'value': 0, u'time': u'2013-05-19T18:10:20.000Z'}, {u'value': 0, u'time': u'2013-05-19T18:10:30.000Z'}, {u'value': 0, u'time': u'2013-05-19T18:10:40.000Z'}, {u'value': 0, u'time': u'2013-05-19T18:10:50.000Z'}, {u'value': 0, u'time': u'2013-05-19T18:11:00.000Z'}, {u'value': 0, u'time': u'2013-05-19T18:11:10.000Z'},
...
...
error = c.metric("sum(aa)")
>>> len(error)
10001
```

**Comment by JoakimSoderberg** [comment]
Note that this is a bug in Cube itself, I filed this issue: https://github.com/square/cube/issues/125
